---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bamboo-pv
  labels:
    app:  bamboo
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "D:/Bamboo"
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: minikube.k8s.io/name
            operator: In
            values:
              - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bamboo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 25Gi
  selector:
    matchLabels:
      app: bamboo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "bamboo"
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "bamboo"
      app.kubernetes.io/instance: "server"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "bamboo"
        app.kubernetes.io/instance: "server"
    spec:
      dnsPolicy: ClusterFirst
      containers:    
        - name: bamboo
          image: atlassian/bamboo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
              hostPort: 8085
            - containerPort: 54663
              hostPort: 54663
          volumeMounts:
            - name: "bamboo-volume"
              mountPath: "/var/atlassian/application-data/bamboo"
      volumes:
        - name: "bamboo-volume"
          persistentVolumeClaim:
            claimName: bamboo-pvc    
--- 
apiVersion: v1
kind: Service
metadata:
  name: "bamboo-svc"
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: "bamboo"
    app.kubernetes.io/instance: "server"
  type: NodePort
  ports:
    - protocol: TCP
      port: 8085
      nodePort: 32377