---
- name: "Prepare the Kubernetes cluster for Linux containers"
  hosts: localhost
  gather_facts: false
  vars:
  tasks:
    - name: "Destroy the secret if it already exist"
      kubernetes.core.k8s:
        definition:
          apiVersion: "v1"
          kind: "Secret"
          metadata:
            name: "{{ SECRET_NAME }}"
            namespace: "{{ SECRET_NAMESPACE }}"
          state: absent