---
- name: "Prepare the Kubernetes cluster for Linux containers"
  hosts: localhost
  gather_facts: true
  vars:
  tasks:
    - name: SECRET_NAME
      debug:
        var: SECRET_NAME
    - name: SECRET_NAMESPACE
      debug:
        var: SECRET_NAMESPACE
    - name: Fetch a list of namespaces
      set_fact:
        projects: "{{ query('kubernetes.core.k8s', api_version='v1', kind='Namespace') }}"
    - name: FACTS
      debug:
        var: ansible_facts
    - name: "Destroy the secret if it already exist"
      kubernetes.core.k8s:
        definition:
          apiVersion: "v1"
          kind: "Secret"
          metadata:
            name: "{{ SECRET_NAME }}"
            namespace: "{{ SECRET_NAMESPACE }}"
          state: absent