---
- name: "Prepare the Kubernetes cluster for Linux containers"
  hosts: localhost
  gather_facts: false
  vars:
  tasks:
    - name: "Destroy the secret if it already exist"
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: "v1"
          kind: "Secret"
          metadata:
            name: "{{ SECRET_NAME }}"
            namespace: "{{ SECRET_NAMESPACE }}"
    - name: "Create the secret"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: "v1"
          kind: "Secret"
          type: "kubernetes.io/tls"
          metadata:
            name: "{{ SECRET_NAME }}"
            namespace: "{{ SECRET_NAMESPACE }}"
          data:
            tls.crt: "{{ TLS_CRT | b64encode }}"
            tls.key: "{{ TLS_KEY | b64encode }}"